version: '3'
services:
  sound-wire-server:
    image: node:22-alpine
    container_name: ars-sonora-server
    tty: true
    working_dir: /app
    ports:
      - '${SERVER_PORT}:3000'
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
    command: ['npm', 'run', 'start:dev']
